input.onButtonPressed(Button.A, function () {
    Pixel_Array.range(0, 0).showColor(neopixel.colors(NeoPixelColors.Red))
    Pixel_Array.range(1, 3).showColor(neopixel.colors(NeoPixelColors.Purple))
    Pixel_Array.range(4, 5).showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(1000)
    servos.P1.stop()
    servos.P2.stop()
})
input.onGesture(Gesture.Shake, function () {
    basic.showIcon(IconNames.Meh)
    music.play(music.builtinPlayableSoundEffect(soundExpression.sad), music.PlaybackMode.UntilDone)
    basic.showIcon(IconNames.Happy)
})
input.onButtonPressed(Button.AB, function () {
    basic.showIcon(IconNames.Fabulous)
    music.setVolume(255)
    servos.P1.setAngle(0)
    music.play(music.stringPlayable("C5 B C5 B A B A G ", 192), music.PlaybackMode.UntilDone)
    servos.P1.stop()
    music.play(music.stringPlayable("B C5 A G F E C D ", 192), music.PlaybackMode.UntilDone)
    servos.P2.setAngle(180)
    music.play(music.stringPlayable("A G F G F G F E ", 250), music.PlaybackMode.UntilDone)
    servos.P2.stop()
    music.setVolume(79)
    basic.showIcon(IconNames.Happy)
})
input.onLogoEvent(TouchButtonEvent.LongPressed, function () {
    music.play(music.builtinPlayableSoundEffect(soundExpression.giggle), music.PlaybackMode.InBackground)
    basic.showIcon(IconNames.Silly)
    basic.pause(800)
    basic.showIcon(IconNames.Happy)
})
input.onSound(DetectedSound.Quiet, function () {
    basic.showIcon(IconNames.Happy)
})
input.onButtonPressed(Button.B, function () {
    Pixel_Array.range(0, 1).showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(1000)
    servos.P1.setAngle(0)
    servos.P2.setAngle(180)
})
input.onSound(DetectedSound.Loud, function () {
    basic.showIcon(IconNames.Confused)
})
let Pixel_Array: neopixel.Strip = null
music.play(music.stringPlayable("C5 B A G F E D C ", 500), music.PlaybackMode.InBackground)
basic.showString("Z")
basic.showString("I")
basic.showString("Z")
basic.showString("O")
basic.showString("T")
Pixel_Array = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
Pixel_Array.range(0, 5).showColor(neopixel.colors(NeoPixelColors.Green))
basic.showIcon(IconNames.Asleep)
basic.showIcon(IconNames.Happy)
basic.pause(3000)
basic.forever(function () {
	
})
